### ISSUE TITLE
Possible conflict with other short-codes

### ISSUE THREAD

**Issue by spetrey** [cgrymala/post-content-shortcodes#1]
Hello! First off, post-content-shortcodes is amazing! Thanks so much for making my life easier for me and my clients.

I noticed an issue with the plugin as it conflicts with another short-code plugin [bootstrap3-shortcodes.](https://github.com/filipstefansson/bootstrap-3-shortcodes)

_Steps to reproduce_
Created `front-page.php` file, set it as static front-page.
Created a separate post with whose id is = 8
Entered the following content inside said post and published:

```
# bootstrap3 shortcode
[column md="12"]
Hello World!
[/column]
```

Back to the front-page, used short-code [post-content id=8] in WYSIWYG, and additional text and publish.
Front-page will ignore content from post with the id=8, but will produce content from the front-page WYSIWYG.

My guess is it is conflicting with other short-codes?

**Comment by cgrymala** [comment]
So sorry for not responding earlier.

This isn't so much a conflict with other shortcodes, as it is somewhat intended behavior of the plugin. Because parsing and outputting shortcodes can be extremely hit-or-miss within another shortcode, especially when potentially truncating the content, this plugin is set up by default to strip out any shortcodes before it processes the content being displayed.

Since all of your content is inside of a shortcode, all of the content is being stripped out.

If you're still trying to get this to work (totally understandable if you've moved on), try adding `shortcodes=1` to your `post-content` shortcode. So, your shortcode would look something like `[post-content id=8 shortcodes=1]`.

With that flag set, the plugin will try to parse shortcodes rather than stripping them out.

**Comment by spetrey** [comment]
@cgrymala No worries—thanks for getting back anyways! Good to know about the `shortcodes=1` flag. 👍
